image:
  repository: ghcr.io/cloudraftio/metrics-app
  tag: "1.1"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

serviceAccount:
  create: true  # Set to true to create the service account, or false to skip
  name: ""      # Optionally provide a custom name for the service account
