replicaCount: 1

image:
  repository: ghcr.io/cloudraftio/metrics-app
  tag: "1.1"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  className: "nginx"
  hosts:
    - host: localhost
      paths:
        - path: /counter
          pathType: Prefix

secrets:
  password: "MYPASSWORD"