apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "metrics-app.fullname" . }}-config
data:
  metrics.py: |
    import collector
    import random

    def trigger_background_collection():
        # Fixed version - no sleep delay, no CPU hogging
        collector.safe_collect()

  collector.py: |
    def safe_collect():
        # Safe version that doesn't execute arbitrary code or hog CPU
        print("Safely collecting metrics")
