apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "metrics-app.fullname" . }}
  labels:
    {{- include "metrics-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "metrics-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "metrics-app.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "metrics-app.fullname" . }}
                  key: password
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP