apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "metrics-app.fullname" . }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /counter
spec:
  rules:
    - host: localhost
      http:
        paths:
          - path: /counter
            pathType: Exact
            backend:
              service:
                name: {{ include "metrics-app.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
