apiVersion: v1
kind: Secret
metadata:
  name: {{ include "metrics-app.fullname" . }}
  labels:
    {{- include "metrics-app.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.secrets.password | b64enc }}